### ISSUE TITLE
How can I join EntySec?

### ISSUE THREAD

**Issue by game-lover** [EntySec/neutron#12]

**Comment by enty8080** [comment]
@game-lover

I can't add you to @EntySec and you know why :(
You know, you were right then about the fact that I should stop copying someone else's code. And I listened to you, I started writing my own projects.

It was strange for me that in the last conversation in **WhatsApp** you called me a **liar** and a **thief**, given the fact that I listened to you and stopped copying someone else's code and deleted everything related to my old activity in this direction.

You just **insulted** me.
And because of that I can't add you to @EntySec because you think that the @EntySec is a group of **liars** and **thiefs**, isn't it?

Best regards
